Crypto Web app
Yosefgeda/metrics-webapp pull request #1
Opened 2023-04-26 13:20 UTC by Yosefgeda

- The project is a single-page application (SPA) built with React and Redux.
- The data retrieved from the API is stored in the Redux store.
- Unit tests created.
- When the page loads, the web app shows the list of Cryptos.
- In the details page, the web app retrieves data from the API to show detailed data in the category.

2023-04-26 14:03 UTC, Reem-lab requested changes
# Hi @Yosefgeda, 👋🏻👋🏻

Great job so far! 💯🤩🚀
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media0.giphy.com/media/LuRH8UGQTPEx2lafrD/giphy-downsized-medium.gif"/>

## Highlights
- No Linters error ✅
- Followed GitFlow 🤩
- Great working on the functionality for getting the data 🔥
- Deployed well ✅
- Great working on the presentation video ✨✨
- Good job working on the tests 🚀💯
- Professional README ⭐

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-26 14:03 UTC, Reem-lab commented on src/components/Home.js
> +
- [ ] Great job for implementing the home page but I recommend to also make the navbar and the first header like the given wireframe so your project is look like the given design since it is very important to  follow these [design guidelines](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs)), including:

Layout: composition and space between elements. 💯⭐🤩
![image](https://user-images.githubusercontent.com/58553711/234594508-af8ca146-dc26-45a6-9866-2c21bb786536.png)



## The navigation is different and you don't have header here! so kindly fix this💯🚀
- your
![image](https://user-images.githubusercontent.com/58553711/234594247-feb3873d-5c5c-4bfd-8eef-6db24ad02f2e.png)


- Given
![image](https://user-images.githubusercontent.com/58553711/234594164-250a2c13-169d-45d6-8f71-4d8b49def6ea.png)

2023-04-26 14:03 UTC, Reem-lab commented on src/components/Details.js
> +      </p>
- [ ] Great job for getting the data from the API but I think according to the design there is no description to display, so you can just remove since in the given design there is some info like you did in the end I know this is additional but it is very important to stick with the requirements as much as possible 🚀💯🤩⭐

- [ ] I think it would be great also here to make the navbar like the design in your details page since it is different in your project 🚀🤩 because in your details page the arrow in the nav important to back to your home page as mentioned in the requirements

![image](https://user-images.githubusercontent.com/58553711/234598853-3971f023-6ebd-4be5-8a9b-0e1b7df80896.png)


### It would be great if you just removed the description and keep the information like the design 💯
- Your
![image](https://user-images.githubusercontent.com/58553711/234596642-7ec0cca5-702d-436b-80ea-ae2b6fb52772.png)

- Given
![image](https://user-images.githubusercontent.com/58553711/234596860-ebe4d992-e047-460d-ac8c-7305494b1c5d.png)

2023-04-26 14:03 UTC, Reem-lab commented on src/components/HomeItems.js
> +  };
- [ ] Great job so far I appreciate your progress but I think you forget one of the most important Technical requirements and it is to filter the data that you retrieve from the API using a Filter stateless component. so kindly implement this filter you can filter using search bar or anything you can make to filter the data 🚀🤩💯⭐⭐

![image](https://user-images.githubusercontent.com/58553711/234598363-a31261bd-fc83-42df-b895-3430f64553b9.png)

2023-04-27 13:46 UTC, amejid requested changes
Hi @Yosefgeda, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

<img src="https://media2.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif"/>

 ## Highlights
- Linter checks passing :heavy_check_mark: 
- Correct workflow :heavy_check_mark: 
- Navigation with React router :heavy_check_mark: 
- Followed design guidelines :heavy_check_mark: 
- Filter implemented :heavy_check_mark: 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-27 13:46 UTC, amejid commented on src/tests/home.test.js
> +
- [ ] You did a great job implementing the changes. :+1: While introducing new changes your tests broke. Kindly make sure all test cases are passing. 🤝️

![image](https://user-images.githubusercontent.com/17243325/234880789-5e11d989-9b04-43c5-b356-72901171f9ab.png)

2023-04-28 05:31 UTC, brainconnect93 approved these changes
## Status: Approved :heavy_check_mark:

Hi @Yosefgeda , 👋 👋  

Your project is complete! Great job for following the project requirement🥇and implementing the changes requested by the previous reviewers. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 


<img src="https://user-images.githubusercontent.com/85113567/184604589-430cf4bc-1d2e-4603-976a-7a48a899ea35.gif" width="600px" height="300px">

## Good Points 👍

- Descriptive Pull Request title & summary. ✔️
- Navigation with React router ✔️
- Followed design guidelines ✔️
- Filter implemented ✔️ 
- All test case passes✔️
- Good use of Git flow ✔️

## Optional changes

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brainconnect93 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-28 05:33 UTC, merged